=== larshelge/nf/nf/trunk/src/main/resources/svx.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://fotballab.no/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    targetNamespace="http://fotballab.no/schema" elementFormDefault="qualified">

<xs:complexType name="XCategory">
	<xs:attribute name="code" use="required" type="xs:string"/>
	<xs:attribute name="name" use="required" type="xs:string"/>
</xs:complexType>

<xs:complexType name="XTeam">
	<xs:attribute name="code" use="required" type="xs:string"/>
	<xs:attribute name="name" use="required" type="xs:string"/>
</xs:complexType>

<xs:complexType name="XPerson">
	<xs:attribute name="code" use="required" type="xs:string"/>
	<xs:attribute name="name" use="required" type="xs:string"/>	
</xs:complexType>

<xs:complexType name="XEvent">
	<xs:attribute name="code" type="xs:string"/>
	<xs:attribute name="date" use="required" type="xs:date"/>
	<xs:attribute name="location" type="xs:string"/>
	<xs:attribute name="homeTeam" type="xs:string"/>
	<xs:attribute name="awayTeam" type="xs:string"/>
</xs:complexType>

<xs:complexType name="XClip">
	<xs:sequence>
		<xs:element name="categories" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="category" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>					
		</xs:element>
		<xs:element name="persons" minOccurs="0" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="person" minOccurs="0" maxOccurs="unbounded" type="xs:string"/>
				</xs:sequence>
			</xs:complexType>					
		</xs:element>
	</xs:sequence>
	<xs:attribute name="start" type="xs:int" use="required"/>
	<xs:attribute name="filename" type="xs:string" use="required"/>
	<xs:attribute name="team" type="xs:string" use="required"/>
	<xs:attribute name="event" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="svx">
	<xs:complexType>
		<xs:sequence>
			
			<!-- Meta-data part -->
			
			<!-- Category -->
			
			<xs:element name="categories" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="category" minOccurs="0" maxOccurs="unbounded" type="XCategory"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Team -->
			
			<xs:element name="teams" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="team" minOccurs="0" maxOccurs="unbounded" type="XTeam"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Person -->
			
			<xs:element name="persons" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="person" minOccurs="0" maxOccurs="unbounded" type="XPerson"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Events -->
			
			<xs:element name="events" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="event" minOccurs="0" maxOccurs="unbounded" type="XEvent"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<!-- Data part -->
			
			<!-- Event -->
			
			<xs:element name="event" minOccurs="0" maxOccurs="1" type="XEvent"/>
			
			<!-- Clips -->
			
			<xs:element name="clips" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="clip" minOccurs="0" maxOccurs="unbounded" type="XClip"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
		</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== larshelge/nf/nf/trunk/src/main/resources/svx-meta-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<svx xmlns="http://fotballab.no/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://fotballab.no/schema http://fotballab.no/schema/svx.xsd">

	<categories>
		<category code="etablert" name="Etablert"/>
		<category code="heading" name="Heading"/>
		<category code="overgang" name="Overgang"/>
		<category code="utsidetouch" name="Utsidetouch"/>
	</categories>
	
	<teams>
		<team code="barcelona" name="Barcelona"/>
		<team code="arsenal" name="Arsenal"/>
	</teams>

	<persons>
		<person code="xavihernandez" name="Xavi Hernandez"/>
		<person code="lionelmessi" name="Lionel Messi"/>
	</persons>

</svx>

=== larshelge/nf/nf/trunk/src/test/resources/svx-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<svx xmlns="http://www.toppfotball.no/schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.toppfotball.no/schema svx.xsd">

	<events>
		<event code="1" date="2009-04-01" location="London" homeTeam="arsenal" awayTeam="barcelona"/>
	</events>
		
	<clips>
		<clip start="4" team="barcelona" filename="v101.mp4" event="1">
			<categories>
				<category>etablert</category>
				<category>heading</category>
			</categories>
			<persons>
				<person>xavihernandez</person>
			</persons>
		</clip>
		<clip start="0" team="barcelona" filename="v102.mp4" event="1">
			<categories>
				<category>overgang</category>
			</categories>
			<persons>
				<person>xavihernandez</person>
			</persons>
		</clip>
		<clip start="0" team="barcelona" filename="v103.mp4" event="1">
			<categories>
				<category>etablert</category>
			</categories>
			<persons>
				<person>lionelmessi</person>
			</persons>
		</clip>
		<clip start="0" team="barcelona" filename="v104.mp4" event="1">
			<categories>
				<category>overgang</category>
				<category>utsidetouch</category>
			</categories>
			<persons>
				<person>lionelmessi</person>
			</persons>
		</clip>
		<clip start="0" team="barcelona" filename="v105.mp4" event="1">
			<persons>
				<person>lionelmessi</person>
			</persons>
		</clip>
	</clips>

</svx>
